[general]
league_id = 1752514
owner = 'Bryan Deagle'
start_week = '2020-09-07'

[espn_scoring]
pass_yards     = 0.04
pass_tds       = 4
pass_ints      = -2
two_pt_conv    = 2
rush_yards     = 0.1
rush_tds       = 6
fumbles        = -2
receptions     = 1
rec_yards      = 0.1
rec_tds        = 6
extra_points   = 1
field_goals    = 4
def_sacks      = 1
def_ints       = 2
fumbles_rec    = 2
def_tds        = 6
safety         = 2

[points_allowed]
0   = 5
7   = 4
14  = 3
18  = 1
28  = 0
35  = -1
46  = -3
200 = -7

[yards_allowed]
100  = 5
200  = 3
300  = 2
350  = 0
400  = -1
450  = -3
500  = -5
550  = -6
1000 = -7

[fantasy_pros]
QB  = ['', '', 'pass_yards', 'pass_tds', 'pass_ints', '', 'rush_yards', 'rush_tds', 'fumbles']
RB  = ['', 'rush_yards', 'rush_tds', 'receptions', 'rec_yards', 'rec_tds', 'fumbles']
WR  = ['receptions', 'rec_yards', 'rec_tds', '', 'rush_yards', 'rush_tds', 'fumbles']
TE  = ['receptions', 'rec_yards', 'rec_tds', 'fumbles']
K   = ['field_goals', '', 'extra_points']
DST = ['def_sacks', 'def_ints', 'fumbles_rec', '', 'def_tds', 'safety', 'points_allowed', 'yards_allowed']

[custom_ids]
Buffalo_Bills            = 'dstbills'
San_Francisco_49ers      = 'dst49ers'
Arizona_Cardinals        = 'dstcardinals'
Kansas_City_Chiefs       = 'dstchiefs'
Tampa_Bay_Buccaneers     = 'dstbuccaneers'
Cleveland_Browns         = 'dstbrowns'
Chicago_Bears            = 'dstbears'
Pittsburgh_Steelers      = 'dststeelers'
Tennessee_Titans         = 'dsttitans'
Baltimore_Ravens         = 'dstravens'
New_England_Patriots     = 'dstpatriots'
Los_Angeles_Rams         = 'dstrams'
Washington_Football_Team = 'dstwashington'
Dallas_Cowboys           = 'dstcowboys'
Cincinnati_Bengals       = 'dstbengals'
Jacksonville_Jaguars     = 'dstjaguars'
Green_Bay_Packers        = 'dstpackers'
Miami_Dolphins           = 'dstdolphins'
Indianapolis_Colts       = 'dstcolts'
New_York_Jets            = 'dstjets'
New_Orleans_Saints       = 'dstsaints'
Minnesota_Vikings        = 'dstvikings'
Seattle_Seahawks         = 'dstseahawks'
Philadelphia_Eagles      = 'dsteagles'
New_York_Giants          = 'dstgiants'
Carolina_Panthers        = 'dstpanthers'
Denver_Broncos           = 'dstbroncos'
Houston_Texans           = 'dsttexans'
Atlanta_Falcons          = 'dstfalcons'
Detroit_Lions            = 'dstlions'
Los_Angeles_Chargers     = 'dstchargers'
Las_Vegas_Raiders        = 'dstraiders'