[general]
league_id = 1752514
owner = 'Bryan Deagle'
start_week = '2020-09-07'

[espn_scoring]
pass_yards     = 0.04
pass_tds       = 4
pass_ints      = -2
two_pt_conv    = 2
rush_yards     = 0.1
rush_tds       = 6
fumbles        = -2
receptions     = 1
rec_yards      = 0.1
rec_tds        = 6
extra_points   = 1
field_goals    = 4
def_sacks      = 1
def_ints       = 2
fumbles_rec    = 2
def_tds        = 6
safety         = 2
