email:
  mg_url: 'https://api.mailgun.net/v3/mg.dea.gl/messages'
  api_key: ''
  to: 'bryan@dea.gl'
  from: 'football@mg.dea.gl'
football:
  team_id: 4
  league_id: 1752514
  espn_s2: ''
  swid: ''
lineup:
  subject: 'Action Required: Set Your Line-Up'
waiver:
  subject: 'Action Required: Waiver Claims'